### ISSUE TITLE
pull push does not work

### ISSUE THREAD

**Issue by cybersiddhu** [gdamore/mangos#105]
I ran ```run.sh``` from the examples...
```shell
$_> go version
go version go1.4.1 linux/amd64
$_> go build
$_> ./run sh                                                                                                                   
NODE1: SENDING "Hello, World."
NODE1: SENDING "Goodbye."
```
The NODE0 does not respond.
```nanocat``` command to work with pull push protocol over tcp.

**Comment by gdamore** [comment]
Confirmed. I just tested myself and reproduced on Darwin.  Furthermore, I've verified that the problem is that we're just exiting too hard, before the message has a chance to be delivered.  I've also verified that setting the mangos.OptionLinger doesn't help.  But sleeping for a second does resolve it.  (Probably sleeping for just a few milliseconds would be sufficient.)  Basically, the issue is that when we exit, we abandon data in queues, or being handled in queues.

For the purposes of the example, adding a sleep solves the problem.  But really we should fix linger.

**Comment by gdamore** [comment]
Actually it looks like the Linger option is missing any backing implementation?!?  Oops?

**Comment by gdamore** [comment]
I think maybe Go and/or the TCP stack is lingering by default, in spite of the docs.  But I need to do a little more work to prove it.

**Comment by gdamore** [comment]
Further investigation, the problem is confirmed *not* to be linger.  The problem is that if you connect, and exit too quickly, you won't have established a TCP connection in the first place.  TCP needs a little bit of time to establish the connection.  Probably 100 msec is plenty.   Its again just TCP slow start.

**Comment by gdamore** [comment]
All this said, I do believe Linger needs work.  What is there is not really sufficient, and is too complex as well.  Our use of channels to indicate that the channel is flushed turns out to be a bit cumbersome, and may actually be racy in that some protocols with multiple end points wind up waiting the full linger time even when empty.

**Comment by cybersiddhu** [comment]
I could confirm your observation and it seems to be generic. In meanwhile, i am using zmq(zmq4 to be precise), for doing push pull and i have to hardcode the timeout right after i send the message.

**Comment by gdamore** [comment]
Fair enough.

I have some bigger changes coming, which I hope will fix this more fully under the hood.

	- Garrett
