### ISSUE TITLE
Unix sockets can't be reused in PUB

### ISSUE THREAD

**Issue by majek** [gdamore/mangos#113]
When on the pub I kill the process and retry it raises

```
listen unix /tmp/xxx.fifo: bind: address already in use
```

There is no reason why rebinding to ipc shoukld fail.

**Comment by gdamore** [comment]
This is an underlying attribute of UNIX domain sockets, and their single biggest limitation.  When a process opens a socket via bind, it creates a name in the filesystem.  If that name already is present, then the bind fails.  This is more or less analogous to the fact that only a single file descriptor can be bound to a TCP port.

One possible solution is to remove the name via unlink(), but that is only safe to do if you know that nobody else is using it.  (Go normally removes the link automatically as part of closing the socket, but if you kill the application it doesn't get a chance to do that graceful cleanup.)

Some programs just blithely remove the link before running.  That's fine, if you know that no other instances are running.  But it would be grossly incorrect for a library to make such assumptions.  Some application specific logic is required to ensure that no conflicting use is present.   (One approach is to use a lock file, or somesuch.  If you can be sure that no other copy of your application is running, you can then remove the link.)

Btw, libnanomsg and zeromq have the same problem, I'm pretty sure.

Its really unfortunate that this situation exists with UNIX domain sockets, and I have thought hard about the problem.  There are inherent races in the existing system, and the only correct solution I can think of is to modify the kernel so that a new type of bind can be done that cleans up any stale file system nodes if no other process is using it.  I could probably make such a change for illumos, but it would not be portable to other systems, and it would take some additional work to expose that through to Go and mangos.

In the meantime, you can remove the name using "rm" or unlink(2), if you're sure its safe to do so.  Knowing that it is safe, and that no other applications will be impacted, is your responsibility though.

A better option might be to use TCP sockets, which don't suffer from this problem at all.

For now, I'm closing this issue, because there is nothing else we can do -- this is an inherent limitation of UNIX domain sockets and not specific to mangos.

**Comment by majek** [comment]
Whooa. Thanks for the response! I did not know that you can't do bind() on existing file. Oh, well, I guess I should go for anonymous unix sockets.

**Comment by gdamore** [comment]
Anonymous UNIX sockets only work with Linux -- they are a Linuxism.

**Comment by sustrik** [comment]
> Btw, libnanomsg and zeromq have the same problem, I'm pretty sure.

Yes, they do.

**Comment by majek** [comment]
(of course I meant "abstract" unix sockets)

**Comment by gdamore** [comment]
Yes, I knew what you meant.

Thinking about it, I think it would be handy for illumos to have an abstract sockets facility too.  I might write one.

**Comment by gdamore** [comment]
Of course, then we'd need a way to express an abstract socket.  Since socket URIs are paths, and cannot contain nuls, we need a new form of URI scheme.  ipc+abstract:// ?

**Comment by cbandy** [comment]
> Go normally removes the link automatically as part of closing the socket, but if you kill the application it doesn't get a chance to do that graceful cleanup.

Is this true of other unhandled signals, or just `kill`?

**Comment by majek** [comment]
The usual scheme for abstract sockets looks like "ipc://@/tmp/abstract.fifo"

**Comment by majek** [comment]
Actually my main concern here is not the error on the existing fifo file, but what happens on the receiver side. So say I restart the publisher, which must include removing the fifo. Will the receiver try to reconnect to a newly recreated fifo file?

**Comment by gdamore** [comment]
Generally, yes, mangos/nanomsg are pretty good about retrying connection attempts.  But, imagine you had a perfectly working server and client that were already connected.  Removing the fifo wouldn't affect them.  So you could have a situation where server instance A and server instance B are both running, historical client connects to A, but a new client winds up connecting to B.  That could be very confusing, even tragic in some circumstances.  Prevention of this scenario with Unix domain sockets falls on the application, sadly.  With TCP the situation is vastly better, which is why I recommend TCP over IPC whenever you can use it.

**Comment by gdamore** [comment]
I like the abstract URI syntax.  We could adopt that I suppose.  We don't support it at present, I think.

With respect to signals -- any signal that terminates the program abruptly will cause this behavior.  Go may catch and handle some gracefully (TERM for example) -- I've not checked that.  But KILL is always uncatchable, and most "crashing" signals (ABRT, SEGV, FPE, etc.) are probably going to behave like KILL.

Signal handling with Go programs is one area I've not explored at all -- to be honest mostly I think its a terrible idea to rely overmuch on them, and understanding that your program can crash for a variety of reasons including SIGKILL, or being killed by the kernel due to out of memory, or even killed with the system as part of a hard-reboot (think power cycle), you need to handle these cases properly.  The only ways I know of to do this properly involve the use of locks, ideally those that are managed by the kernel so that when the process holding the lock goes away the kernel can reap the lock.  The discussion of this problem is a little outside of the scope of this bug. :-)
