### ISSUE TITLE
Possible to add goquic

### ISSUE THREAD

**Issue by fire** [gdamore/mangos#135]
Hi Mangos developers,

I hope it would be possible to add https://github.com/devsisters/goquic as an encryption library for mangos. The hope is that quic makes it into nanomsg as an encrypted transport.

Do you have any suggestions on how to do this?

**Comment by reqshark** [comment]
encryption seems a bit out of the normal scope of transport, no?

**Comment by fire** [comment]
https://github.com/gdamore/mangos/tree/master/transport/tlstcp seems to have been implemented.

**Comment by fire** [comment]
I forgot to mention that QUIC is a UDP encrypted connection library. https://docs.google.com/document/d/1gY9-YNDNAB1eip-RTPbqphgySwSNSDHLq9D5Bty4FSU

**Comment by gdamore** [comment]
Look at the websocket implementation.  As you can see it is not hard to add new transports to mangos. 

That said it seems the quic library is not yet stable enough that I would support integrating it in our code base. 

Adding it to nanomsg is likely to be much harder since nanomsg is ill designed to cope with anything that isn't file descriptor based. This is why nanomsg still doesn't have tls support.

**Comment by gdamore** [comment]
Given that the above implementation is written in C, with just some Go-external linkage,and its very young yet (still), I'm going to close this as will not fix.  That doesn't mean you can't write your own transport and plug it in -- you could.  And when QUIC gets to a level of stability (ideally with a pure Go implementation) where it can reliably be used for both client and server side, then I'll be quite happy to revisit this issue.

Frankly, I think Google is looking at QUIC as mostly a private experiment between Chrome and its servers, and I don't really expect QUIC to remain extant for very long -- mostly because I think its likely that Google will continue to further evolve it -- its clear that Google wants to integrate these improvements into TCP itself somehow.

Anyway, I'll continue to monitor the status of QUIC, but I don't want to leave this issue outstanding in an indeterminate state.
