### ISSUE TITLE
Race condition in simple Send()/Recv() code

### ISSUE THREAD

**Issue by majek** [gdamore/mangos#139]
I have a fairly simple application that does the following:

```
pub := misc.NanomsgPub(nanomsgOutAddr)

var tmpBuffer [4096 + 16]byte
for {
		n, addr, err := udp.ReadFromUDP(buf)
		data := buf[:n]

			t := tmpBuffer[:]
			copy(t, data)
			data = t[:len(data)]

		err = pub.Send(data)
}
```

Where the nanomsgpub is:

```
func NanomsgPub(nanomsgOutAddr string) mangos.Socket {
	pub, err := mangospub.NewSocket()
	if err != nil {
		fmt.Fprintf(os.Stderr, "[!] nanomsg.NewSubSocket() %v\n", err.Error())
		os.Exit(3)
	}

	pub.SetOption(mangos.OptionWriteQLen, 2048)
	pub.SetOption(mangos.OptionReadQLen, 2048)
	pub.SetOption(mangos.OptionNoDelay, false)

	if strings.HasPrefix(nanomsgOutAddr, "ipc:///") {
		// ignore error
		os.Remove(nanomsgOutAddr[6:])
	}

	fmt.Fprintf(os.Stderr, "[+] Publishing to nanomsg SUB on %q\n", nanomsgOutAddr)
	pub.AddTransport(ipc.NewTransport())
	pub.AddTransport(tcp.NewTransport())
	if err := pub.Listen(nanomsgOutAddr); err != nil {
		fmt.Fprintf(os.Stderr, "[!] nanomsg.Listen(%q) %v\n", nanomsgOutAddr, err.Error())
		os.Exit(3)
	}
	return pub
}
```

Sadly, when reading messages from the ipc endpoint, many are:
 - truncated
 - have additional data dangling

This goes away when I switch to go-nanomsg library. I suspect mangos doesn't copy the data from the given buffer when I do "send", and I overwrite the data soon on next loop iteration. Also, the application is pretty high volume (tens of thousands messages a second)

**Comment by gdamore** [comment]
Sounds ugly.  I'll have a look.  Does this happen if you switch to TCP?  Are both sender and receiver mangos?  Does it make a difference which one you change?  What are the message sizes?

**Comment by gdamore** [comment]
> On Jul 17, 2015, at 8:06 AM, Garrett D'Amore <garrett@damore.org> wrote:
> 
> Sounds ugly.  I'll have a look.  Does this happen if you switch to TCP?  Are both sender and receiver mangos?  Does it make a difference which one you change?  What are the message sizes?
> 

While the symptoms you describe would be explained by your hypothesis, I just checked the code and I don’t think that’s the case.  The send routine is pretty darn simple, and it does perform a data copy into a separate Message.  I also run this code with the test suite with the race checker turned on, and believe me, when I’ve had races, it does an excellent job of finding and reporting them.  Here’s the Send routine:

func (s *Socket) Send(b []byte, flags int) (int, error) {

        if flags != 0 {
                return -1, errNoFlag
        }

        m := mangos.NewMessage(len(b))
        m.Body = append(m.Body, b...)

        // Legacy nanomsg uses the opposite semantic for negative and
        // zero values than mangos.  A bit unfortunate.
        switch {
        case s.sto > 0:
                s.sock.SetOption(mangos.OptionSendDeadline, s.sto)
        case s.sto == 0:
                s.sock.SetOption(mangos.OptionSendDeadline, -1)
        case s.sto < 0:
                s.sock.SetOption(mangos.OptionSendDeadline, 0)
        }

        return len(b), s.sock.SendMsg(m)
}


Btw, all the finagling you’re doing with temp buffers is unnecessary.  You can just do:

err = pub.Send(buf[:n])

I think that would be easier to reason about than the copies you’re making into additional scratch buffers, etc.  It would also be faster.  I’m assuming that you are doing these in a single threaded loop as you’ve described, and there isn’t some level of async going on that you’ve not included.  The difference in indentation level makes me wonder what code you’ve removed.

While I’m not saying that mangos doesn’t have a bug here (it may well have), it would be good to know that our test case is minimally complex so that we fully exonerate it and lay the blame squarely on mangos.

	- Garrett


> Sent from my iPhone
>

**Comment by majek** [comment]
https://gist.github.com/majek/5ad981a6f647719a9749

```
marek@ubuntu-saucy:~/cloudflare/gatewatcher$ ./a 
[+] Publishing to nanomsg SUB on "ipc:///tmp/xx"
[+] Receiving from nanomsg PUB on "ipc:///tmp/xx"
data=116 len=33
data=116 len=15
data=116 len=199
data=116 len=187
data=116 len=129
data=116 len=134
data=116 len=57
data=116 len=172
data=116 len=72
data=116 len=164
```

**Comment by gdamore** [comment]
Your gist was very helpful.  I will investigate and be back in touch soon.  Btw what platform and go version are you using?  I don't think it's tied to that but in case I have trouble reproducing knowing where you hit it might help.

**Comment by gdamore** [comment]
Ok, so I've found the bug.  It wasn't in compat, it was in the simplistic Send()/Recv() interfaces.  Note that I pretty much never use those interfaces as they are suboptimal from a performance standpoint (extra data copies).  I've got a fix, writing a formal test case for it, and will integrate the fix shortly.

**Comment by majek** [comment]
awesome. thanks
