### ISSUE TITLE
is bug? the recv message can't read header

### ISSUE THREAD

**Issue by RyouZhang** [gdamore/mangos#142]
conn.go line 42
func (p *conn) Recv()(*Message, error)

msg = NewMessage(int(sz))
msg.Body = msg.Body[0:sz]

**Comment by gdamore** [comment]
No, its not a bug.  We read the size from the transport header, and then the entire message afterwards.  The size (and if there were any, any other transport specific headers) are not part of the message that is delivered to the application.

Conceivably we could capture transport state here and pass it to the Pipe along with the message, but it turns out that for connected pipes there is no state that is interesting at this time.  (The interesting state is all gathered during connection establishment time.)

Note that Scalability Protocol headers (such as Req/Rep headers) are included in the size, and are delivered with the message.  The pattern specific code will parse and strip those from the message later in the code path.
