### ISSUE TITLE
core.go addPipe

### ISSUE THREAD

**Issue by wenfang** [gdamore/mangos#143]
line 69:
if l == nil && p == nil {

should be 

if l == nil && d == nil {   ???

**Comment by gdamore** [comment]
You are correct.  Nice catch.

It it turns out that its harmless, since that condition should never ever occur (see the comment above that suggests it could be an assertion, if we had those in Go).

Anyway, we ought to fix it.  Do you want to send me a pull request with a fix?  Otherwise I can take care of it.
