### ISSUE TITLE
porthook_test.go:194: Client got wrong # calls, 1 != 2

### ISSUE THREAD

**Issue by glycerine** [gdamore/mangos#149]
linux amd64/ go1.5.1. mangos 774a176919d40f4a5da37f1cb5da5158430b3580

~~~
$ cd tests; go test -v
...
=== RUN   TestPortHook
--- FAIL: TestPortHook (0.10s)
    porthook_test.go:77: Testing Add Hook
    porthook_test.go:154: Waiting a bit...
    porthook_test.go:68: Hook called - 0!
    porthook_test.go:68: Hook called - 0!
    porthook_test.go:68: Hook called - 1!
    porthook_test.go:171: Exp C[0]: Add CLI tcp://127.0.0.1:59093 Open
    porthook_test.go:171: Exp C[1]: Rem CLI tcp://127.0.0.1:59093 Closed
    porthook_test.go:174: Got C[0]: Add CLI tcp://127.0.0.1:59093 Open
    porthook_test.go:177: Exp S[0]: Add SRV tcp://127.0.0.1:59093 Open
    porthook_test.go:177: Exp S[1]: Rem SRV tcp://127.0.0.1:59093 Closed
    porthook_test.go:180: Got S[0]: Add SRV tcp://127.0.0.1:59093 Open
    porthook_test.go:180: Got S[1]: Rem SRV tcp://127.0.0.1:59093 Closed
    porthook_test.go:194: Client got wrong # calls, 1 != 2
~~~

**Comment by gdamore** [comment]
I'm thinking maybe I can just add a delay here to resolve the inherent race...  stay tuned.

**Comment by gdamore** [comment]
So, that seems to work, and I believe I understand why.  The issue is that when we close a peer, the local side notices the close asynchronously, and closes in a go routine.  If we execute too quickly, or the go routine is scheduled too slowly, then the hook function won't get called before we get to the verification point in the test.

This does underscore one other problem, but I'm not sure its worth fixing.  The PortHook actually executes on a Pipe, and its possible that the Pipe outlasts (just slightly) the socket. 

Fixing that would be desirable, but the current framework can't easily do it without introducing a nightmare of race condition fights.  In any event, folks registering PortHooks probably should not care if the hook gets executed slightly after the socket is closed.  In general, most applications using this never close their sockets anyway.
