### ISSUE TITLE
using it with nsq

### ISSUE THREAD

**Issue by joeblew99** [gdamore/mangos#166]
i am wondering if this can be used with a MQ like NSQ http://nsq.io/

**Comment by gdamore** [comment]
Generally most brokered MQs provide their own transport layers.  mangos (and nanomsg from which it it is inspired and with which it interoperates) are brokerless.

There is some overlap in the patterns, such as Pub/Sub, etc., and you can use either mangos or NSQ to solve a variety of problems.

However, there are quite different approaches.  Many MQs provide message persistence and reliable delivery; generally mangos and nanomsg do not, and only offer best effort style delivery.

If your problem doesn't require persistence or reliable delivery, then mangos will probably offer a simpler solution, and may be better suited for your needs.

If you need message persistence and reliability, then a true brokered MQ is going to be better.

Now, there's not particular reason why an MQ couldn't use mangos or libnanomsg as its underlying transport.  And there's not really a strong reason why mangos couldn't use an MQ as a transport either.  But as far as I know, nobody has done work in either of these directions, most likely because there generally is little benefit to doing so, and the work is sufficiently non-trivial to simply not be worth the effort.

I hope this answers your question.  I'm going to close this "issue" since there wasn't really a code deliverable or a bug here.

**Comment by joeblew99** [comment]
thats a really thorough explanation - thank you, it helps.

NSQ can store messages on disk, and thats the main reason i was asking.
But i can imaging then that Mango could also provide disk backing for messages ?

**Comment by gdamore** [comment]
One could make a transport that did this yes.  However I've no desire to do so as I don't see replacing true mqs as a design goal for mangos or nanomsg. 

Better would be to write a broker that used mangos as its transport as a separate application.

**Comment by joeblew99** [comment]
Ah yes.
So each micrio service has mango integrated, and so manages the persistence.

I am very interested in using the web sockets everywhere, even up to the web clients etc
