### ISSUE TITLE
Web sock lib can use the built in one

### ISSUE THREAD

**Issue by joeblew99** [gdamore/mangos#168]
Gorilla is great, but there is a websocket client and server in golang trr now.
I have been using it and its solid.

It's also in with the http/2 package.

Might be worth trying it out for mangoes

**Comment by gdamore** [comment]
Actually, we started with the builtin golang websocket framework.  I converted to the gorilla framework recently -- see this changeset: 324ed4eef9d68f083d541e502db0671f0d627235

The reason I did this was that I needed the ability to limit message sizes to prevent a DoS type of attack.  The stock golang framework doesn't have any ability to tune the limit on the rx size -- see ws.SetReadLimit() in the gorilla websocket.

Anyway, you can mix and match this with stock golang servers, because we implement the ServeHTTP and http Handler interfaces that are specified with in the stock golang APIs.

I'd of course preferred to avoid introducing a 3rd party package dependency, but given the limitation that exists in golang's framework, I didn't see much choice.  When golang is updated to support tuning the maximum RX size, then I'd consider going back to it.

**Comment by joeblew99** [comment]
OK makes sense.

Why not suggest it to golang tram ? Worth a shot :)
