### ISSUE TITLE
Cycle detection for STAR

### ISSUE THREAD

**Issue by tylertreat** [gdamore/mangos#40]
I wanted to start the discussion on how we can handle cycles with the STAR protocol. I find this protocol extremely useful, but I think it's unreasonable to require systems to avoid cycles.

It seems the simplest solution is to just allow cycles and add a TTL and, optionally, an ID on messages. This way, messages won't propagate infinitely. Applications which need to ensure idempotency can make use of an ID, whether its part of the protocol or the message body itself. Obviously the downside is there's additional overhead with adding more onto the message.

**Comment by gdamore** [comment]
I've thought about this.  I think cycle detection would be very useful.  A monotonically increasing id combined with a sender id would probably do the trick but would require all participants to keep a cache of recently seen messages.   A map of last id indexed by sender id is sufficient.

I'm glad someone else finds STAR useful. It is only in mangos so we have a lot of freedom to change as needed.

**Comment by gdamore** [comment]
Simple answer here will be to just add a hop count, and give each message a TTL.  Loops will cause messages to be seen more than once, but the loops will terminate gracefully after some limit.  (And the hop count should be configurable-- for this protocol I'd probably set it fairly low, say 4, to minimize the damage caused by loops.)
