### ISSUE TITLE
Responder Timeout Notification

### ISSUE THREAD

**Issue by adamclerk** [gdamore/mangos#61]
I've looked through the docs and the Surveyor source. I've noticed that we're dropping any messages that exceed the timeout. Which looks a little passive for my tastes. 

- We receive a message from a responder
- If the time taken is greater than the timeout
- We drop the message.

I'm assuming the implementation would have to change to have a more active timeout.
IE: Have the surveyor to pass a message when a responder has timed out.

Am I wrong in my assessment? Was there something I missed?

**Comment by gdamore** [comment]
I believe libnanomsg does the same.  When you consider that there may be many responders, and that you really have no idea whether an incoming message was from just now, or from hours ago, this is really the best approach.  The cooked socket mode filters these so that the application only gets survey results he expected.

HOWEVER, if an application wants to receive all responses, and is prepared to sort through them to figure out which responses are valid survey results, the Raw socket is available.  Raw sockets perform no filtering whatsoever. Note that in this case, the surveyor will be responsible for appending a survey ID to the header before sending, and for stripping it on receipt.

So, RAW is what you're after -- but really I think you're not after that at all.

**Comment by gdamore** [comment]
I'm going to go ahead and close this for now.  If you disagree with this, let me know, and we can discuss further.
