### ISSUE TITLE
mangos causes goq TestSubmitRemote to fail

### ISSUE THREAD

**Issue by glycerine** [gdamore/mangos#80]
Hi Garrett, I tried the latest mangos master (c6a3acbbf1e563e41fd93c44a071a1743b7bf97a), but its not passing the goq test suite. I made a branch of goq for you, so it points at github.com/gdamore/mangos, and it has all tests enabled. See https://github.com/glycerine/goq/tree/all-tests-mangos  . Since I have production uses, I've kept the master branch of goq back a little until we can get tests passing again. - Jason

specifically: TestSubmitRemote fails, and TestSubmitShutdownToRemoteJobServ goes into infinite loop.
Other tests may fail but the infinite loop blinds me to the at the moment.

snippet from the test output below.
linux amd64/go1.4
~~~
=== RUN TestSubmitRemote

  remotely, over nanomsg, goq should be able to submit job to the server
    and then server should get back the expected output from the job run
 took 0 10msec sleeps for address 'tcp://10.0.0.6:2776' to become available.

 took 0 10msec sleeps for address 'tcp://10.0.0.6:2776' to become available.
[pid 10374] spawned a new external JobServ with pid 10391
2015-02-08 07:57:31.309 -0800 PST **** [jobserver pid 10391] listening for jobs on 'tcp://10.0.0.6:2776', output t\
o 'o'. GOQ_HOME is '/home/jaten/dev/cnet/go/src/github.com/glycerine/goq/tempgoqtestdir205132413'.
�

Errors:

  * /home/jaten/dev/cnet/go/src/github.com/glycerine/goq/fetch_test.go
  Line 48: - err during submit job: send time out

  goroutine 74 [running]:
  github.com/glycerine/goq.(*Submitter).SubmitJob(0xc208140c60, 0xc2080349c0)
    /home/jaten/dev/cnet/go/src/github.com/glycerine/goq/sub.go:77 +0x1fb
  github.com/glycerine/goq.func·031()
    /home/jaten/dev/cnet/go/src/github.com/glycerine/goq/fetch_test.go:48 +0x31c
  github.com/glycerine/goq.TestSubmitRemote(0xc20806e090)
    /home/jaten/dev/cnet/go/src/github.com/glycerine/goq/fetch_test.go:71 +0x157
  testing.tRunner(0xc20806e090, 0xd851e0)
    /home/jaten/pkg/go1.4/go/src/testing/testing.go:447 +0xbf
~~~

**Comment by gdamore** [comment]
Crap.  So I created a regression I guess.  I will investigate.

**Comment by gdamore** [comment]
So the problem here is a demand for different semantics.  Earlier, in TestSendShouldTimeout005 you had a demand that send timeout when there is no underlying transport present.  But *these* tests fail if we do timeout in this situation, because you do the job submit before firing off the worker.  Because of that, the connect() is still waiting, and there is no place to send your message yet, so it sits in the queue.

Basically, you can't have both semantics.  Given that you've filed *this* one as a bug, and the other 005 test isn't integrated in goq yet, I'm going to revert the code that sets the queue size to 0.  Then you can choose which semantic you want.  If you want send to timeout when there are no underlying transports available, set the WriteQLen to 0.  If you don't want it to timeout, but to queue it for later delivery, then leave it a the default non-zero value.

**Comment by glycerine** [comment]
My apologies if anything seemed like a demand.

All these tests pass under C nanomsg.  How does it manage to provide semantics that mangos does not?

**Comment by gdamore** [comment]
That is an excellent question.  And one that I cannot explain.  On the face of it - at least to me - the two semantics are diametrically opposed.  There may be something subtle that I'm missing here though but I can't see it.

**Comment by gdamore** [comment]
Btw if I used too strong language around the word demand then please accept my apologies.  I suppose request would have been better. 

Still if you can help me understand how the semantics are different then I can try to at least to accommodate.  For the life of me I cannot see how you could want to get a timeout in the one case but not in the other. 

There could be a level of tuning here.  Eg accept and buffer only a single request?  It seems to me that depending on the depth of the buffer is a bad idea though. 

I will look at this some more and see if I can come up with anything.

**Comment by gdamore** [comment]
Thanks for your patience.  I think I’ve fixed all known goq test failures now.  A little background (this is interesting).

1. You were starting the job server in a separate program.  This takes a little time to start up.

2. You then try to dial the server.  This is going to fail because the job server isn’t ready yet.  Not only that, but the Connect() itself is async, so when you try to send, it puts the message in a channel waiting for a connection to be established.

3. At this point, we have a message sitting waiting for delivery, or until it times out (1 second), and transport to send it over.

4. Eventually the connect is supposed to be redialed, and the connection reestablished.  HOWEVER, there was a hard coded reconnect interval of — 1 second!  Add to that a few milliseconds for TCP to establish (empirically I found it to be about 3 msec for all overheads), and now that message in the queue is timing out!

5. So nanomsg used a retry interval of 100 msec instead of 1 sec, and a backoff (double the time each time) — actually nanomsg uses an unbounded exponential back off by default, which means it could wait *hours*, days, weeks, even years — between reconnect attempts.  Stupid default! 

I fixed this by using a similar approach as nanomsg — 100 msec with exponential backoff (though I bounded it at 1 minute by default) — and then set the queue depth back to zero.

Note that there *are* edge cases where your tests won’t catch certain failure modes.  For example, if the worker goroutine grabs the message from the queue, but the underlying transport can’t deliver it due to transport errors (disconnect?), you won’t notice that error at the API level.  I think nanomsg has some similar limitations because of its asynchronous event handling.  The only way I can really fix this is to add a callback routine on the message that gets called when the message is delivered to the transport.  I might yet do that, but it won’t be available unless you use the mangos native API.

(And note that delivery to the transport still does not guarantee receipt by the far end peer — the far end transport could drop the message in its kernel, etc.)

Anyway, this was interesting — it helped iron out one of the edge cases in mangos, so I’m grateful for that.

Thanks for your patience through all this.

The bug fix is here:

https://github.com/gdamore/mangos/commit/b0c40a49bdffc3bf651552e06aa905cdcd2bd419 <https://github.com/gdamore/mangos/commit/b0c40a49bdffc3bf651552e06aa905cdcd2bd419>

	- Garrett

**Comment by glycerine** [comment]
Excellent detective work, and very interesting! Thanks Garrett.

**Comment by gdamore** [comment]
> On Feb 9, 2015, at 2:59 PM, Jason E. Aten, Ph.D. <notifications@github.com> wrote:
> 
> Excellent detective work, and very interesting! Thanks Garrett.
> 
> 

Thanks. Please let me know if this is now suitable to your needs.  If it is, I’ll probably tag it as a release.  I have more stuff to do, but I think tagging semi-stable releases is probably useful.

	- Garrett

**Comment by glycerine** [comment]
Hi Garrett, 

Seems to work well. I would tag it. 

Best,
Jason
